### ISSUE TITLE
Expose and adjust silence level threshold

### ISSUE THREAD

**Issue by leolobato** [fulldecent/FDSoundActivatedRecorder#20]
Sorry for not including this on the last release. :)

I see `microphoneLevel ` actually discard values below -85dB, which would be considered silence.

In my experience using the library, I've noticed a fairly silent room (windows closed, empty house) meters around -44dB without anyone speaking, and presenting this as a visual level cue to the user is helpful to let them know if the library will or not easily detect speech (and a silent ambient also contributes to a better speech recognition, which is why I am using this library).

So if they see the visual microphone level "empty", they will understand they are at a good environment for speech recognition. If they see the level moving (or even half-full), they'll understand they're at a noisy ambient and will speak closer to the microphone (or switch to a headset).

I'm creating a new pull request with two separate commits:

- Expose a `microphoneLevelThreshold` property and;
- Changing its default value from -85 to -44db

Feel free to discard the default value change if you think the previous was better.

**Comment by fulldecent** [comment]
Thank you for the research and contribution. I would like to do some research before changing this number just so that I know the new number will be good (even though -44 is most definitely better than -85). Could you please share which cases you have tried using a quiet room, windows closed:

 * iPhone 5 or later, no attachments
 * iPad Air 1 or later, no attachments
 * Any iOS device, Apple Lightning headphones, headphones not in ear
 * Any iOS device, Apple mini phono headphones, headphones not in ear
 * Any iOS device, those knockoff Apple mini phono headphones that everyone has, not in ear
 * Any iOS device, any headphones, in ear

I suppose the lowest value we can get with any of the above methods minus a few dB should be the minimum.

**Comment by fulldecent** [comment]
I have completed testing in all these environments and 44 is pretty close for all real world scenarios.
